# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stocks App 2.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stocks App 2.0
pod 'Charts'

end
